services:
  # Serviço do Banco de Dados
  product-db:
    build: ./productdb
    container_name: product-db
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      # Cross-check: Comando completo para evitar erro de mapping
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql

  # Serviço da API Go
  product-api:
    build: ./productapi
    container_name: product-api
    ports:
      - "8081:8081"
    environment:
      - env=docker # Cross-check: Força o config.Load() a ler docker.yml
    depends_on:
      product-db:
        condition: service_healthy

volumes:
  db-data: