services:
  product-db:
    build: ./productdb
    container_name: product-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=products_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    healthcheck:
      # Cross-check: Comando para verificar se o MySQL está aceitando conexões
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  product-api:
    build: ./productapi
    container_name: product-api
    ports:
      - "8081:8081"
    environment:
      # Cross-check: Variável 'env' que nosso loader em Go utiliza para carregar 'docker.yml'
      - env=docker
    volumes:
      - ./productapi/configs:/configs
    depends_on:
      product-db:
        # Cross-check: Condição crucial para evitar erro de 'connection refused' no boot da API
        condition: service_healthy