# Cross-check: Versão estável do MySQL conforme o roadmap
FROM mysql:8.0

# Copia os scripts locais para a pasta de inicialização automática do container
COPY ./create_scripts/ /docker-entrypoint-initdb.d/